spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://localhost:5432/shop
    username: admin
    password: 52669
  flyway:
    baseline-on-migrate: true
server:
 port: 8081
